main: net.starlegacy.StarLegacy
name: IonCore
version: SNAPSHOT
api-version: 1.18
load: POSTWORLD
authors: [PeterCrawley, MicleBrick]
website: https://horizonsend.net/
depend: [LuckPerms, Vault, WorldEdit, Citizens, DiscordSRV]
softdepend: [dynmap]